BEGIN ;

DROP TABLE biblio CASCADE ;
DROP TABLE star CASCADE ;
DROP TABLE designation CASCADE ;
DROP TABLE coord CASCADE ;
DROP TABLE star_principal CASCADE ;
DROP TABLE band CASCADE ;
DROP TABLE frame CASCADE ;
DROP TABLE photorun CASCADE ;
DROP TABLE runset CASCADE ;
DROP TABLE photoobj CASCADE ;
DROP TABLE objcrossid CASCADE ;

COMMIT ;
